# fly.toml app configuration file generated for obsidian-capture-scraper on 2026-03-09T17:49:35-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'obsidian-capture-scraper'
primary_region = 'sjc'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
